### ISSUE TITLE
parsing shortName from title automatically

### ISSUE THREAD

**Issue by gshirato** [AlexIGD/visualsurvey#1]
## Context

When users of visualSurvey.net are adding new scientific papers into the system, they are required to fill in the shortName field for each entry. Often, the shortName is simply a segment of the title, typically the portion preceding the first colon. In cases where a suitable short name isn't evident, users would find themselves copying and pasting the full title into the shortName field.

## Problem or idea

The manual duplication of information from title to shortName is time-consuming, especially when dealing with large numbers of papers, and can lead to inconsistencies or errors.

### Proposed solutions:

- Automatically populate the shortName field by parsing the string before the ":" in the title. This automation would save time and ensure consistency.

- Make the shortName field optional rather than required. This would be beneficial for users who often find themselves duplicating the full title when a suitable shortName is not apparent.

**Comment by AlexIGD** [comment]
Solved with update on 12.07.23
Shorttitle is not a required field anymore.
If the title has a ":" the shorttitle will be using the text before the ":", else the shorttitle will be set to an empty string.
However, the user can then edit the shorttitle manually.
