### ISSUE TITLE
Highlighting an edited or created paper

### ISSUE THREAD

**Issue by gshirato** [AlexIGD/visualsurvey#2]
## Context

On visualSurvey.net, when users are adding new scientific papers or editing existing ones, especially in bulk, it becomes a challenge to quickly identify the paper they have just worked.

## Problem or idea

The current user interface does not provide a clear and immediate indication of which paper has just been created or edited. This can lead to confusion and inefficiency as users must manually scan through the list of papers to locate their most recent work, which can be especially cumbersome when handling large quantities of papers.

## Solution or next step

The implementation of a feature that temporarily highlights a paper that a user has just created or edited, possibly through a distinct color change. The highlight should ideally remain visible until the user starts working on another paper or until the end of their current session.

**Comment by AlexIGD** [comment]
Solved with update on 12.07.23
On the /modify page the last clicked paper or newly added paper now have a highlighting border
