### ISSUE TITLE
Feature Request - Option to Remove Subcategory Thumbnail

### ISSUE THREAD

**Issue by gshirato** [AlexIGD/visualsurvey#3]
## Context

When managing the subcategories, there is currently an option to replace the thumbnail of a subcategory but not to remove it entirely.

## Problem

The absence of an option to remove a thumbnail can lead to situations where an irrelevant or outdated image remains visible due to an unintended operation or the lack of a suitable replacement.

## Solution

I propose the addition of a feature that allows for the complete removal of a subcategory's thumbnail, possibly by clicking on the current thumbnail to show the options ("remove" and "replace")

**Comment by gshirato** [comment]
<img width="1354" alt="Screenshot 2023-07-12 at 15 34 25" src="https://github.com/AlexIGD/visualsurvey/assets/23716732/6602d4ae-e781-4e5b-8d38-90739fa1466d">

BTW, labels do not seem accessible. Is there a way for us to add labels on an issue?

**Comment by AlexIGD** [comment]
Github only allows people with write access to the repository to apply labels
