### ISSUE TITLE
Bug - Thumbnail Persistence After Subcategory Deletion

### ISSUE THREAD

**Issue by gshirato** [AlexIGD/visualsurvey#4]
## Context

There seems to be a bug related to the handling of thumbnail images for subcategories. When a subcategory, complete with a thumbnail image, is deleted, and then a new subcategory is added, the thumbnail image from the deleted subcategory incorrectly appears for the newly added subcategory.

## Steps to reproduce

1. Delete a subcategory that has a thumbnail image
2. Add a new subcategory
3. The new subcategory erroneously displays the thumbnail image from the previously deleted subcategory

## Expected Behavior

Upon creating a new subcategory, especially following the deletion of a subcategory, it should be initialized without a thumbnail image.

## Actual Behavior

The new subcategory appears with the thumbnail image that was associated with the previously deleted subcategory.

**Comment by gshirato** [comment]
I confirmed that after closing the edit panel the thumbnail image with the previously deleted subcategory is actually gone.

**Comment by AlexIGD** [comment]
Thank you, I think I know where the bug is.
